import {
    Play,
    Coins,
    Rocket,
    User,
    Package,
    Network,
    Layers,
    Shuffle,
    TrendingDown,
    Users,
    TrendingUp,
    UserPlus,
    CheckCircle2,
    Receipt,
    Timer,
    Dices,
    UserCheck,
    RotateCw,
    GitBranch,
    SplitSquareHorizontal,
    Database,
    Webhook,
    BarChart3,
    Users2,
    Activity,
    DollarSign,
    RefreshCw,
} from 'lucide-react'
import { BuilderNodeCategory, PaletteNodeDef } from './types'

/** Categories that may only have a single instance on the canvas at a time. */
export const SINGLE_INSTANCE_CATEGORIES: BuilderNodeCategory[] = ['token', 'launchType']

export const CATEGORY_LABELS: Record<BuilderNodeCategory, string> = {
    execution: 'Execution',
    token: 'Token',
    launchType: 'Launch Type',
    trade: 'Trades',
    trigger: 'Trigger',
    conditional: 'Conditionals',
    utility: 'Utility',
}

export const CATEGORY_ACCENT: Record<BuilderNodeCategory, { border: string; bg: string; text: string; ring: string }> = {
    execution:   { border: 'border-lime-500',    bg: 'bg-lime-500/5',    text: 'text-lime-500',    ring: 'ring-lime-500' },
    token:       { border: 'border-blue-500',    bg: 'bg-blue-500/5',    text: 'text-blue-500',    ring: 'ring-blue-500' },
    launchType:  { border: 'border-violet-500',  bg: 'bg-violet-500/5',  text: 'text-violet-500',  ring: 'ring-violet-500' },
    trade:       { border: 'border-emerald-500', bg: 'bg-emerald-500/5', text: 'text-emerald-500', ring: 'ring-emerald-500' },
    trigger:     { border: 'border-amber-500',   bg: 'bg-amber-500/5',   text: 'text-amber-500',   ring: 'ring-amber-500' },
    conditional: { border: 'border-rose-500',    bg: 'bg-rose-500/5',    text: 'text-rose-500',    ring: 'ring-rose-500' },
    utility:     { border: 'border-cyan-500',    bg: 'bg-cyan-500/5',    text: 'text-cyan-500',    ring: 'ring-cyan-500' },
}

export const PALETTE_ITEMS: PaletteNodeDef[] = [
    // ── Execution ──────────────────────────────────────────────────────────
    {
        category: 'execution',
        nodeType: 'executionNode',
        subtype: 'manualRun',
        label: 'Manual Run',
        description: 'Manually starts execution at whatever node it connects to. Drop one anywhere to test a webhook, a trade chain, or a full launch in isolation — connect its output to any node’s left-side exec pin.',
        icon: Play,
        inputs: 0,
        outputs: 1,
        inputTypes: [],
        outputTypes: ['exec'],
    },

    // ── Token ──────────────────────────────────────────────────────────────
    {
        category: 'token',
        nodeType: 'tokenNode',
        subtype: 'tokenToLaunch',
        label: 'Token to Launch',
        description: 'The token being launched. Starting point of the graph.',
        icon: Coins,
        inputs: 0,
        outputs: 1,
        inputTypes: [],
        outputTypes: ['token'],
    },

    // ── Launch Type ────────────────────────────────────────────────────────
    {
        category: 'launchType',
        nodeType: 'launchTypeNode',
        subtype: 'dev0DevOnly',
        label: 'Dev 0 (Dev Only)',
        description: 'Dev buy into block 0 — dev wallet only, no bundle.',
        icon: User,
        inputs: 1,
        outputs: 1,
        inputTypes: ['token'],
        outputTypes: ['config'],
    },
    {
        category: 'launchType',
        nodeType: 'launchTypeNode',
        subtype: 'dev0DevBundle',
        label: 'Dev 0 (Dev + Bundle)',
        description: 'Dev buy into block 0 with an additional Jito bundle of wallets.',
        icon: Rocket,
        inputs: 1,
        outputs: 1,
        inputTypes: ['token'],
        outputTypes: ['config'],
    },
    {
        category: 'launchType',
        nodeType: 'launchTypeNode',
        subtype: 'bundled',
        label: 'Bundled',
        description: 'Coordinated multi-wallet bundle at launch.',
        icon: Package,
        inputs: 1,
        outputs: 1,
        inputTypes: ['token'],
        outputTypes: ['config'],
    },
    {
        category: 'launchType',
        nodeType: 'launchTypeNode',
        subtype: 'swarm',
        label: 'Swarm',
        description: 'Post block-0 swarm launch.',
        icon: Network,
        inputs: 1,
        outputs: 1,
        inputTypes: ['token'],
        outputTypes: ['config'],
    },

    // ── Trades ──────────────────────────────────────────────────────────��──
    // Trade nodes pass config through — they consume and re-emit the execution
    // context so trades can be chained: LaunchType → Trade → Trade → …
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'bundledJito',
        label: 'Bundled (Jito)',
        description: 'Jito bundle of coordinated trades.',
        icon: Layers,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['config'],
    },
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'staggeredBuy',
        label: 'Staggered Buy',
        description: 'Time-spread buys across wallets with randomized delay.',
        icon: Shuffle,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['config'],
    },
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'staggeredSell',
        label: 'Staggered Sell',
        description: 'Time-spread sells across wallets with randomized delay. Sell % applied to live balances at runtime.',
        icon: TrendingDown,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['config'],
        defaultData: { sellPct: 100, delayMinSeconds: 5, delayMaxSeconds: 30 },
    },
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'humanVolume',
        label: 'Human Volume',
        description: 'Generates human-like trading patterns.',
        icon: Users,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['config'],
    },
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'trendingVolume',
        label: 'Trending Volume',
        description: 'Boosts volume for trending lists.',
        icon: TrendingUp,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['config'],
    },
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'holdersMaker',
        label: 'Holders Maker',
        description: 'Distributes tokens to increase holder count.',
        icon: UserPlus,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['config'],
    },

    // ── Triggers ───────────────────────────────────────────────────────────
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'launchConfirmation',
        label: 'Launch Confirmation',
        description: 'Waits for confirmation that the launch transaction landed.',
        icon: CheckCircle2,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'txConfirmation',
        label: 'Tx Confirmation',
        description: 'Waits for confirmation of a specific transaction.',
        icon: Receipt,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'timerSet',
        label: 'Timer: Set',
        description: 'Waits a fixed number of seconds before continuing.',
        icon: Timer,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
        defaultData: { seconds: 5 },
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'timerRandomInterval',
        label: 'Timer: Random Interval',
        description: 'Waits a randomized interval between a min/max before continuing.',
        icon: Dices,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
        defaultData: { minSeconds: 5, maxSeconds: 30 },
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'humanInTheLoop',
        label: 'Human In The Loop',
        description: 'Pauses and waits for a human to manually continue.',
        icon: UserCheck,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'marketCapThreshold',
        label: 'Market Cap Threshold',
        description: 'Polls until the token market cap crosses a target value.',
        icon: BarChart3,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
        defaultData: { targetMarketCapUSD: 50000, direction: 'above', pollIntervalSeconds: 10 },
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'holderCountThreshold',
        label: 'Holder Count Threshold',
        description: 'Polls until the number of unique token holders crosses a target.',
        icon: Users2,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
        defaultData: { targetHolderCount: 100, direction: 'above', pollIntervalSeconds: 15 },
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'volumeThreshold',
        label: 'Volume Threshold',
        description: 'Polls until cumulative trading volume crosses a target SOL amount.',
        icon: Activity,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
        defaultData: { targetVolumeSol: 10, pollIntervalSeconds: 10 },
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'priceTarget',
        label: 'Price Target',
        description: 'Polls until the token price crosses a target value.',
        icon: DollarSign,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
        defaultData: { targetPriceUSD: 0.001, direction: 'above', pollIntervalSeconds: 5 },
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'retryBackoff',
        label: 'Retry / Backoff',
        description: 'Retries the previous step with exponential backoff on failure.',
        icon: RefreshCw,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['signal'],
        defaultData: { maxRetries: 3, initialDelaySeconds: 5, multiplier: 2, maxDelaySeconds: 60 },
    },

    // ── Utility ────────────────────────────────────────────────────────────
    {
        category: 'utility',
        nodeType: 'dataNode',
        subtype: 'dataMapper',
        label: 'Data',
        description: 'Extracts token and launch context into a named key-value payload for downstream nodes.',
        icon: Database,
        inputs: 1,
        outputs: 1,
        inputTypes: ['config'],
        outputTypes: ['data'],
    },
    {
        category: 'utility',
        nodeType: 'webhookNode',
        subtype: 'webhook',
        label: 'Webhook',
        description: 'POSTs the incoming data payload to an HTTP endpoint and waits for a response.',
        icon: Webhook,
        inputs: 1,
        outputs: 1,
        inputTypes: ['data'],
        outputTypes: ['signal'],
        defaultData: { url: '', authType: 'none', authValue: '', customHeaders: [] },
    },

    // ── Conditionals ───────────────────────────────────────────────────────
    {
        category: 'conditional',
        nodeType: 'conditionalNode',
        subtype: 'loop',
        label: 'Loop',
        description: 'Repeats the connected branch a number of times.',
        icon: RotateCw,
        inputs: 1,
        outputs: 2,
        inputTypes: ['signal'],
        outputTypes: ['signal', 'signal'],
        defaultData: { maxIterations: 3 },
    },
    {
        category: 'conditional',
        nodeType: 'conditionalNode',
        subtype: 'ifThen',
        label: 'If / Then',
        description: 'Branches into two paths based on a condition.',
        icon: GitBranch,
        inputs: 1,
        outputs: 2,
        inputTypes: ['signal'],
        outputTypes: ['signal', 'signal'],
        defaultData: { condition: '' },
    },
    {
        category: 'conditional',
        nodeType: 'conditionalNode',
        subtype: 'switch',
        label: 'Switch',
        description: 'Branches into multiple paths.',
        icon: SplitSquareHorizontal,
        inputs: 1,
        outputs: 'dynamic',
        inputTypes: ['signal'],
        outputTypes: ['branch'],
        defaultData: { branchCount: 2, branchLabels: ['Case 1', 'Case 2'] },
    },
]

export const PALETTE_GROUPS: { category: BuilderNodeCategory; items: PaletteNodeDef[] }[] = (
    ['execution', 'token', 'launchType', 'trade', 'trigger', 'conditional', 'utility'] as BuilderNodeCategory[]
).map((category) => ({
    category,
    items: PALETTE_ITEMS.filter((item) => item.category === category),
}))
