import {
    Coins,
    Rocket,
    User,
    Package,
    Network,
    Layers,
    Shuffle,
    Users,
    TrendingUp,
    UserPlus,
    CheckCircle2,
    Receipt,
    Timer,
    Dices,
    UserCheck,
    RotateCw,
    GitBranch,
    SplitSquareHorizontal,
} from 'lucide-react'
import { BuilderNodeCategory, PaletteNodeDef } from './types'

/** Categories that may only have a single instance on the canvas at a time. */
export const SINGLE_INSTANCE_CATEGORIES: BuilderNodeCategory[] = ['token', 'launchType']

export const CATEGORY_LABELS: Record<BuilderNodeCategory, string> = {
    token: 'Token',
    launchType: 'Launch Type',
    trade: 'Trades',
    trigger: 'Trigger',
    conditional: 'Conditionals',
}

export const CATEGORY_ACCENT: Record<BuilderNodeCategory, { border: string; bg: string; text: string }> = {
    token:       { border: 'border-blue-500',    bg: 'bg-blue-500/5',    text: 'text-blue-500' },
    launchType:  { border: 'border-violet-500',  bg: 'bg-violet-500/5',  text: 'text-violet-500' },
    trade:       { border: 'border-emerald-500', bg: 'bg-emerald-500/5', text: 'text-emerald-500' },
    trigger:     { border: 'border-amber-500',   bg: 'bg-amber-500/5',   text: 'text-amber-500' },
    conditional: { border: 'border-rose-500',    bg: 'bg-rose-500/5',    text: 'text-rose-500' },
}

export const PALETTE_ITEMS: PaletteNodeDef[] = [
    // Token
    {
        category: 'token',
        nodeType: 'tokenNode',
        subtype: 'tokenToLaunch',
        label: 'Token to Launch',
        description: 'The token being launched. Starting point of the graph.',
        icon: Coins,
        inputs: 0,
        outputs: 1,
    },

    // Launch Type
    {
        category: 'launchType',
        nodeType: 'launchTypeNode',
        subtype: 'dev0DevOnly',
        label: 'Dev 0 (Dev Only)',
        description: 'Dev buy into block 0 — dev wallet only, no bundle.',
        icon: User,
        inputs: 1,
        outputs: 1,
    },
    {
        category: 'launchType',
        nodeType: 'launchTypeNode',
        subtype: 'dev0DevBundle',
        label: 'Dev 0 (Dev + Bundle)',
        description: 'Dev buy into block 0 with an additional Jito bundle of wallets.',
        icon: Rocket,
        inputs: 1,
        outputs: 1,
    },
    {
        category: 'launchType',
        nodeType: 'launchTypeNode',
        subtype: 'bundled',
        label: 'Bundled',
        description: 'Coordinated multi-wallet bundle at launch.',
        icon: Package,
        inputs: 1,
        outputs: 1,
    },
    {
        category: 'launchType',
        nodeType: 'launchTypeNode',
        subtype: 'swarm',
        label: 'Swarm',
        description: 'Post block-0 swarm launch.',
        icon: Network,
        inputs: 1,
        outputs: 1,
    },

    // Trades
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'bundledJito',
        label: 'Bundled (Jito)',
        description: 'Jito bundle of coordinated trades.',
        icon: Layers,
        inputs: 1,
        outputs: 1,
    },
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'staggeredBuy',
        label: 'Staggered Buy',
        description: 'Time-spread buys across wallets with randomized delay.',
        icon: Shuffle,
        inputs: 1,
        outputs: 1,
    },
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'humanVolume',
        label: 'Human Volume',
        description: 'Generates human-like trading patterns.',
        icon: Users,
        inputs: 1,
        outputs: 1,
    },
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'trendingVolume',
        label: 'Trending Volume',
        description: 'Boosts volume for trending lists.',
        icon: TrendingUp,
        inputs: 1,
        outputs: 1,
    },
    {
        category: 'trade',
        nodeType: 'tradeNode',
        subtype: 'holdersMaker',
        label: 'Holders Maker',
        description: 'Distributes tokens to increase holder count.',
        icon: UserPlus,
        inputs: 1,
        outputs: 1,
    },

    // Trigger
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'launchConfirmation',
        label: 'Launch Confirmation',
        description: 'Waits for confirmation that the launch transaction landed.',
        icon: CheckCircle2,
        inputs: 1,
        outputs: 1,
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'txConfirmation',
        label: 'Tx Confirmation',
        description: 'Waits for confirmation of a specific transaction.',
        icon: Receipt,
        inputs: 1,
        outputs: 1,
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'timerSet',
        label: 'Timer: Set',
        description: 'Waits a fixed number of seconds before continuing.',
        icon: Timer,
        inputs: 1,
        outputs: 1,
        defaultData: { seconds: 5 },
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'timerRandomInterval',
        label: 'Timer: Random Interval',
        description: 'Waits a randomized interval between a min/max before continuing.',
        icon: Dices,
        inputs: 1,
        outputs: 1,
        defaultData: { minSeconds: 5, maxSeconds: 30 },
    },
    {
        category: 'trigger',
        nodeType: 'triggerNode',
        subtype: 'humanInTheLoop',
        label: 'Human In The Loop',
        description: 'Pauses and waits for a human to manually continue.',
        icon: UserCheck,
        inputs: 1,
        outputs: 1,
    },

    // Conditionals
    {
        category: 'conditional',
        nodeType: 'conditionalNode',
        subtype: 'loop',
        label: 'Loop',
        description: 'Repeats the connected branch a number of times.',
        icon: RotateCw,
        inputs: 1,
        outputs: 2,
        defaultData: { maxIterations: 3 },
    },
    {
        category: 'conditional',
        nodeType: 'conditionalNode',
        subtype: 'ifThen',
        label: 'If / Then',
        description: 'Branches into two paths based on a condition.',
        icon: GitBranch,
        inputs: 1,
        outputs: 2,
        defaultData: { condition: '' },
    },
    {
        category: 'conditional',
        nodeType: 'conditionalNode',
        subtype: 'switch',
        label: 'Switch',
        description: 'Branches into multiple paths.',
        icon: SplitSquareHorizontal,
        inputs: 1,
        outputs: 'dynamic',
        defaultData: { branchCount: 2, branchLabels: ['Case 1', 'Case 2'] },
    },
]

export const PALETTE_GROUPS: { category: BuilderNodeCategory; items: PaletteNodeDef[] }[] = (
    ['token', 'launchType', 'trade', 'trigger', 'conditional'] as BuilderNodeCategory[]
).map((category) => ({
    category,
    items: PALETTE_ITEMS.filter((item) => item.category === category),
}))
