


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "hypopg" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "index_advisor" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."owners" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."owners" OWNER TO "postgres";


ALTER TABLE "public"."owners" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."owners_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "img_url" "text"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


ALTER TABLE "public"."profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."profiles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tokens" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "symbol" "text" NOT NULL,
    "description" "text",
    "dev_wallet_id" bigint NOT NULL,
    "contract_address" "text",
    "website_url" "text",
    "twitter_url" "text",
    "telegram_handle" "text",
    "logo_url" "text",
    "launched" boolean DEFAULT false,
    "mint_secret_key" "text" NOT NULL,
    "token_meta_url" "text",
    "owner_id" bigint
);


ALTER TABLE "public"."tokens" OWNER TO "postgres";


ALTER TABLE "public"."tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tokens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."transactions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "transaction_time" timestamp with time zone NOT NULL,
    "wallet_id" bigint NOT NULL,
    "transaction_signature" "text" NOT NULL,
    "transaction_actions" "jsonb",
    "fee_in_lamports" bigint DEFAULT '0'::bigint NOT NULL,
    "priority_fee_in_lamports" bigint DEFAULT '0'::bigint NOT NULL,
    "token_pair" "text" NOT NULL
);


ALTER TABLE "public"."transactions" OWNER TO "postgres";


ALTER TABLE "public"."transactions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."transactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."vanity_keypairs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "mint_secret_key" "text" NOT NULL,
    "available" boolean DEFAULT true NOT NULL,
    "contract_address" "text" NOT NULL
);


ALTER TABLE "public"."vanity_keypairs" OWNER TO "postgres";


ALTER TABLE "public"."vanity_keypairs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."vanity_contract_addresses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."wallet_groups" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "owner_id" bigint NOT NULL
);


ALTER TABLE "public"."wallet_groups" OWNER TO "postgres";


ALTER TABLE "public"."wallet_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."wallet_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."wallet_type" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."wallet_type" OWNER TO "postgres";


ALTER TABLE "public"."wallet_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."wallet_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."wallets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "public_key" "text" NOT NULL,
    "secret_key" "text" NOT NULL,
    "funded" boolean DEFAULT false NOT NULL,
    "wallet_type_id" bigint,
    "solana_balance_in_lamports" bigint DEFAULT '0'::bigint NOT NULL,
    "owner_id" bigint,
    "group_id" bigint,
    "token_holdings" "jsonb",
    "profile_id" bigint
);


ALTER TABLE "public"."wallets" OWNER TO "postgres";


ALTER TABLE "public"."wallets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."wallets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."owners"
    ADD CONSTRAINT "owners_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."owners"
    ADD CONSTRAINT "owners_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tokens"
    ADD CONSTRAINT "tokens_created_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tokens"
    ADD CONSTRAINT "tokens_mint_key" UNIQUE ("mint_secret_key");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vanity_keypairs"
    ADD CONSTRAINT "vanity_contract_addresses_contract_address_key" UNIQUE ("mint_secret_key");



ALTER TABLE ONLY "public"."vanity_keypairs"
    ADD CONSTRAINT "vanity_contract_addresses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vanity_keypairs"
    ADD CONSTRAINT "vanity_keypairs_contract_address_key" UNIQUE ("contract_address");



ALTER TABLE ONLY "public"."wallet_groups"
    ADD CONSTRAINT "wallet_groups_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."wallet_groups"
    ADD CONSTRAINT "wallet_groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."wallet_type"
    ADD CONSTRAINT "wallet_type_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."wallets"
    ADD CONSTRAINT "wallets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."wallets"
    ADD CONSTRAINT "wallets_private_key_key" UNIQUE ("secret_key");



ALTER TABLE ONLY "public"."wallets"
    ADD CONSTRAINT "wallets_public_key_key" UNIQUE ("public_key");



ALTER TABLE ONLY "public"."tokens"
    ADD CONSTRAINT "tokens_created_dev_wallet_id_fkey" FOREIGN KEY ("dev_wallet_id") REFERENCES "public"."wallets"("id");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_wallet_id_fkey" FOREIGN KEY ("wallet_id") REFERENCES "public"."wallets"("id");



ALTER TABLE ONLY "public"."wallets"
    ADD CONSTRAINT "wallets_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."wallet_groups"("id");



ALTER TABLE ONLY "public"."wallets"
    ADD CONSTRAINT "wallets_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."owners"("id");



ALTER TABLE ONLY "public"."wallets"
    ADD CONSTRAINT "wallets_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."wallets"
    ADD CONSTRAINT "wallets_wallet_type_id_fkey" FOREIGN KEY ("wallet_type_id") REFERENCES "public"."wallet_type"("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
























































































































































































































GRANT ALL ON TABLE "public"."owners" TO "anon";
GRANT ALL ON TABLE "public"."owners" TO "authenticated";
GRANT ALL ON TABLE "public"."owners" TO "service_role";



GRANT ALL ON SEQUENCE "public"."owners_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."owners_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."owners_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."profiles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."profiles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."profiles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tokens" TO "anon";
GRANT ALL ON TABLE "public"."tokens" TO "authenticated";
GRANT ALL ON TABLE "public"."tokens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."transactions" TO "anon";
GRANT ALL ON TABLE "public"."transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vanity_keypairs" TO "anon";
GRANT ALL ON TABLE "public"."vanity_keypairs" TO "authenticated";
GRANT ALL ON TABLE "public"."vanity_keypairs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."vanity_contract_addresses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vanity_contract_addresses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vanity_contract_addresses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."wallet_groups" TO "anon";
GRANT ALL ON TABLE "public"."wallet_groups" TO "authenticated";
GRANT ALL ON TABLE "public"."wallet_groups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."wallet_groups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."wallet_groups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."wallet_groups_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."wallet_type" TO "anon";
GRANT ALL ON TABLE "public"."wallet_type" TO "authenticated";
GRANT ALL ON TABLE "public"."wallet_type" TO "service_role";



GRANT ALL ON SEQUENCE "public"."wallet_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."wallet_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."wallet_type_id_seq" TO "service_role";



GRANT SELECT ON TABLE "public"."wallets" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "public"."wallets" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "public"."wallets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."wallets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."wallets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."wallets_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































