// Generated by `import-template preset`. Safe to edit by hand afterwards —
// re-running will overwrite, so copy anything you want to keep.

import type { TemplatePreset } from "@site/schema";

export const preset: TemplatePreset = {
  "id": "original",
  "templateId": "spacex-ipo",
  "templateVersion": "1.0.0",
  "name": "Original",
  "isDefault": true,
  "theme": {
    "id": "spacex-ipo-original",
    "name": "Original theme",
    "schemaVersion": 1,
    "mode": "dark",
    "core": {
      "colors": {
        "background": "#000",
        "surface": "#111111",
        "primary": "#fff",
        "primaryHover": "white",
        "onPrimary": "#000",
        "secondary": "#1a1a1a",
        "text": "#fff",
        "textMuted": "#e0e0e0",
        "border": "#222222",
        "overlay": "#000000",
        "success": "#22c55e",
        "warning": "#f59e0b",
        "error": "#ef4444"
      },
      "typography": {
        "fontFamilyBase": "\"Manrope\",Verdana,Geneva,Tahoma,sans-serif",
        "baseFontSize": "18px",
        "scaleRatio": 1.3229,
        "scaleRatioMobile": 1.2107,
        "fontWeightNormal": 400,
        "fontWeightBold": 700,
        "lineHeightBase": 1.7,
        "lineHeightHeading": 1.1,
        "letterSpacingWide": "2px",
        "headingTransform": "uppercase",
        "kickerTransform": "uppercase"
      },
      "spacing": {
        "unit": "8px",
        "containerMaxInline": "1200px",
        "contentMaxInline": "700px",
        "sectionPaddingBlock": "80px",
        "sectionPaddingInline": "8%",
        "radius": "0px"
      },
      "motion": {
        "speed": ".3s",
        "easing": "ease",
        "respectReducedMotion": true
      },
      "breakpoints": {
        "md": "768px"
      },
      "button": {
        "textTransform": "uppercase",
        "paddingBlock": "14px",
        "paddingInline": "28px",
        "borderWidth": "0px"
      }
    },
    "semantic": {
      "navBackground": "rgba(0,0,0,.2)",
      "navForeground": "white",
      "mobileMenuBackground": "#333",
      "footerBackground": "#000",
      "footerForeground": "#888",
      "footerBorder": "#222"
    },
    "templates": {
      "spacex-ipo": {
        "headerBlur": "blur(8px)",
        "sectionMinHeight": "100vh"
      }
    }
  },
  "content": {
    "schemaVersion": 1,
    "meta": {
      "fqdn": "",
      "title": "SpaceX IPO",
      "description": "The SpaceXIPO coin celebrates the launch of $SPCX.",
      "keywords": "spacex, spacexipo, meme coin, dexscreener, pump.fun, social media links",
      "locale": "en",
      "noindex": true
    },
    "brand": {
      "name": "TODO"
    },
    "hero": {
      "kicker": "Invest in Exploration",
      "title": "Celebrating the launch",
      "body": [
        "In 2020, SpaceX returned America's ability to fly NASA astronauts to and from the International Space Station on American vehicles.",
        "The SpaceXIPO coin celebrates the launch of $SPCX."
      ],
      "backgroundImage": {
        "id": "5164d7ef-16d4-48f2-9ef6-34dac9329881",
        "stagingKey": "_templates/spacex-ipo@1.0.0/seed/banner/",
        "url": "/seed/banner/original.jpeg",
        "alt": "",
        "decorative": false,
        "focalX": 0.5,
        "focalY": 0.5,
        "variants": {
          "original": "/seed/banner/original.jpeg"
        },
        "seedPath": "banner"
      },
      "overlayOpacity": 0.35,
      "overlayDirection": "uniform",
      "crossAlign": "start",
      // The CA-copy widget is no longer a CTA slot (see manifest.ts and
      // overrides.json's sections.launch.ignoreCta) — this entry was the
      // flattened text extract.ts read back before the widget had its own
      // slots. Nothing maps to hero.ctas[0] anymore, so it stays empty.
      "ctas": [],
      "contentAnchor": "block-center"
    },
    "sections": [
      {
        "id": "c5e501df-1cc0-42f8-808a-d9e2e47c01b7",
        "slug": "ipo",
        "order": 0,
        "enabled": true,
        "navLabel": "IPO",
        "showInNav": true,
        "kicker": "SpaceX IPO",
        "title": "$SPCX",
        "backgroundImage": {
          "id": "8081704f-5c18-4e41-9778-bec5c3afae69",
          "stagingKey": "_templates/spacex-ipo@1.0.0/seed/img1/",
          "url": "/seed/img1/original.jpeg",
          "alt": "",
          "decorative": false,
          "focalX": 0.5,
          "focalY": 0.5,
          "variants": {
            "original": "/seed/img1/original.jpeg"
          },
          "seedPath": "img1"
        },
        "overlayOpacity": 0.35,
        "overlayDirection": "uniform",
        "contentAnchor": "block-center",
        "crossAlign": "start",
        "type": "prose",
        "body": [
          "SpaceX was listed on the Nasdaq under the ticker symbol $SPCX on June 12, 2026. The company intended to raise $75 billion by selling 555.6 million shares at $135 apiece, targeting a mind-boggling valuation of roughly $1.75 trillion. However, after a day of trading the stock now values the company at $2.1 trillion."
        ]
      },
      {
        "id": "c62bc799-dcd1-4420-817d-f6c2d79a120f",
        "slug": "offering",
        "order": 1,
        "enabled": true,
        "navLabel": "Offering",
        "showInNav": true,
        "kicker": "Access",
        "title": "A non-traditional offering",
        "backgroundImage": {
          "id": "667f98b6-4a1b-44a8-bd8b-54bcb96a2f12",
          "stagingKey": "_templates/spacex-ipo@1.0.0/seed/img2/",
          "url": "/seed/img2/original.jpeg",
          "alt": "",
          "decorative": false,
          "focalX": 0.5,
          "focalY": 0.5,
          "variants": {
            "original": "/seed/img2/original.jpeg"
          },
          "seedPath": "img2"
        },
        "overlayOpacity": 0.35,
        "overlayDirection": "uniform",
        "contentAnchor": "block-center",
        "crossAlign": "start",
        "type": "prose",
        "body": [
          "Unlike standard IPOs where financial institutions dominate, SpaceX is offering individual investors up to 30% of the deal at the same price. Brokerages like Robinhood, Fidelity, and SoFi have lowered their minimum participation requirements to as little as $2,000.",
          "Because of the listing's enormous scale, the Nasdaq-100 has created a new fast-entry rule allowing SpaceX to join the benchmark after just 15 days of trading."
        ]
      },
      {
        "id": "297b5a13-addc-4f87-8eab-37ac23600853",
        "slug": "coin",
        "order": 2,
        "enabled": true,
        "navLabel": "Coin",
        "showInNav": true,
        "kicker": "The SpaceX IPO Coin",
        "title": "From Launch to Orbit",
        "backgroundImage": {
          "id": "d1d05ed4-1353-4f22-8c4e-35f18569dcb4",
          "stagingKey": "_templates/spacex-ipo@1.0.0/seed/img3/",
          "url": "/seed/img3/original.jpeg",
          "alt": "",
          "decorative": false,
          "focalX": 0.5,
          "focalY": 0.5,
          "variants": {
            "original": "/seed/img3/original.jpeg"
          },
          "seedPath": "img3"
        },
        "overlayOpacity": 0.35,
        "overlayDirection": "uniform",
        "contentAnchor": "block-center",
        "crossAlign": "start",
        "type": "prose",
        "body": [
          "SpaceXIPO coin is intended to sustain growth by transitioning from initial hype to continuous trading activity.."
        ],
        "cta": {
          "label": "SpaceX",
          "href": "#",
          "external": false,
          "variant": "primary"
        }
      }
    ],
    "social": [
      {
        "id": "bec82625-31d7-46ec-b11d-d957b34b2afd",
        "platform": "x-twitter",
        "label": "x-twitter",
        "url": "https://x.com/spacexipo_coin",
        "showInNav": true,
        "showInHero": false
      },
      {
        "id": "bd6368ff-bef5-45f3-ace9-d59085f4ebf6",
        "platform": "telegram",
        "label": "telegram",
        "url": "https://t.me/spacexipo_coin",
        "showInNav": true,
        "showInHero": false
      }
    ],
    // Hand-added — author-preset has no extraction path for modules yet, so
    // overrides.json's anonymize entry for modules.token.contractAddress
    // never reaches a generated draft to act on. Applied here by hand
    // instead: this must NOT be the source's real address (see
    // overrides.json), same reasoning as brand.name/social[].url. copyLabel
    // and copyConfirmation come straight from the source widget's own text.
    //
    // Accessibility follow-up for the eventual approved copy-to-clipboard
    // script: see ../../../../../templates/spacex-ipo/TODO.md. Not here,
    // because this file is generated (preset refuses to clobber it, but the
    // header above still says "generated") — the TODO lives somewhere no
    // pipeline step ever touches.
    "modules": {
      "token": {
        "contractAddress": "0x0000000000000000000000000000000000000000",
        "copyLabel": "Click to copy:",
        "copyConfirmation": "Coin identifier copied to clipboard"
      }
    },
    "footer": {
      "disclaimer": "TODO",
      "legal": {
        "copyrightYear": "auto"
      },
      "links": []
    }
  },
  "mustReplace": [
    "brand.name",
    "meta.title",
    "meta.description",
    "hero.title",
    "social[].url",
    // Anonymized to the zero address above — every site launches its own
    // token and must supply its own contract, same rationale as brand.name.
    "modules.token.contractAddress"
  ]
};
