// Generated by `import-template emit`, then HAND-EDITED.
//
// Re-running emit will not overwrite this file. Selector mappings, section
// bounds and module support all live here and are review work.

import type { TemplateManifest } from "@site/schema";

export const manifest: TemplateManifest = {
  "id": "spacex-ipo",
  "name": "Spacex Ipo",
  "description": "Imported from spacex-ipo.",
  "version": "1.0.0",
  "previewImage": "_templates/spacex-ipo@1.0.0/preview.png",
  "rendererKey": "slotted",
  "flow": "vertical",
  "supportedSectionTypes": [
    "prose"
  ],
  "sectionCount": {
    "min": 3,
    "max": 3
  },
  "supportsModules": [],
  "requiredContent": [
    "hero.title",
    "meta.title"
  ],
  "dependencies": [],
  "imageAspect": {
    "hero": "16/9",
    "section": "16/9",
    "card": "4/3",
    "gallery": "1/1"
  },
  "usesThemeKeys": [
    "core.colors.background",
    "core.colors.onPrimary",
    "core.colors.overlay",
    "core.colors.primary",
    "core.colors.primaryHover",
    "core.colors.text",
    "core.colors.textMuted",
    "core.motion.speed",
    "core.spacing.contentMaxInline",
    "core.spacing.sectionPaddingBlock",
    "core.spacing.sectionPaddingInline",
    "core.typography.baseFontSize",
    "core.typography.fontFamilyBase",
    "core.typography.headingTransform",
    "core.typography.kickerTransform",
    "core.typography.letterSpacingWide",
    "core.typography.lineHeightBase",
    "core.typography.lineHeightHeading",
    "semantic.footerBackground",
    "semantic.footerBorder",
    "semantic.footerForeground",
    "semantic.mobileMenuBackground",
    "semantic.navBackground",
    "semantic.navForeground"
  ],
  "customThemeSchema": {
    "headerBlur": {
      "type": "select",
      "label": "Header Blur",
      "default": "blur(8px)"
    },
    "sectionMinHeight": {
      "type": "length",
      "label": "Section Min Height",
      "default": "100vh"
    }
  },
  "capabilities": {
    "hasStickyNav": true,
    "hasMobileDrawer": true,
    "supportsPerSectionBackground": true
  },
  "kind": "slotted",
  "slotted": {
    "sourceKey": "spacex-ipo@1",
    "slots": [
      {
        "selector": "#launch .kicker",
        "path": "hero.kicker",
        "mode": "text"
      },
      {
        "selector": "#launch .content h1",
        "path": "hero.title",
        "mode": "text"
      },
      {
        "selector": "#launch .content p:nth-of-type(1)",
        "path": "hero.body[0]",
        "mode": "text"
      },
      {
        "selector": "#launch .content p:nth-of-type(2)",
        "path": "hero.body[1]",
        "mode": "text"
      },
      {
        "selector": "#launch .btn",
        "path": "hero.ctas[0]",
        "mode": "link"
      },
      {
        "selector": "#ipo .kicker",
        "path": "sections[0].kicker",
        "mode": "text"
      },
      {
        "selector": "#ipo .content h2",
        "path": "sections[0].title",
        "mode": "text"
      },
      {
        "selector": "#ipo .content p:nth-of-type(2)",
        "path": "sections[0].body[0]",
        "mode": "text"
      },
      {
        "selector": "#offering .kicker",
        "path": "sections[1].kicker",
        "mode": "text"
      },
      {
        "selector": "#offering .content h2",
        "path": "sections[1].title",
        "mode": "text"
      },
      {
        "selector": "#offering .content p:nth-of-type(1)",
        "path": "sections[1].body[0]",
        "mode": "text"
      },
      {
        "selector": "#offering .content p:nth-of-type(2)",
        "path": "sections[1].body[1]",
        "mode": "text"
      },
      {
        "selector": "#coin .kicker",
        "path": "sections[2].kicker",
        "mode": "text"
      },
      {
        "selector": "#coin .content h2",
        "path": "sections[2].title",
        "mode": "text"
      },
      {
        "selector": "#coin .content p",
        "path": "sections[2].body[0]",
        "mode": "text"
      },
      {
        "selector": "#coin .btn",
        "path": "sections[2].cta",
        "mode": "link"
      }
    ],
    "repeaters": [],
    "sanitize": {
      "approvedScripts": [],
      "allowedOrigins": [],
      "stripSelectors": []
    },
    "metaInsertSelector": "head",
    "rewriteAnchors": true,
    "sectionNodes": [
      {
        "path": "sections[0]",
        "selector": "#ipo",
        "navSelector": "a[href$=\"#ipo\"]"
      },
      {
        "path": "sections[1]",
        "selector": "#offering",
        "navSelector": "a[href$=\"#offering\"]"
      },
      {
        "path": "sections[2]",
        "selector": "#coin",
        "navSelector": "a[href$=\"#coin\"]"
      }
    ],
    "cssBackgrounds": [
      {
        "path": "hero.backgroundImage",
        "selector": ".hero",
        "pseudo": "before"
      },
      {
        "path": "sections[1].backgroundImage",
        "selector": ".starship",
        "pseudo": "before"
      },
      {
        "path": "sections[2].backgroundImage",
        "selector": ".human",
        "pseudo": "before"
      },
      {
        "path": "sections[3].backgroundImage",
        "selector": ".network",
        "pseudo": "before"
      }
    ],
    "sourceHash": "cc12a8f81207f3687beecc84558e3e9a78fcd133bc658c52251bead96e72ef38",
    "cssTokenized": {
      "source": "inline",
      "cssHash": "0ec898642b960150e496ce2ebfa0bac9e3647c6aaa5be0ba13756c63044a863b"
    }
  }
} as TemplateManifest;
