// Generated by `import-template emit`, then HAND-EDITED.
//
// Re-running emit will not overwrite this file. Selector mappings, section
// bounds and module support all live here and are review work.

import type { TemplateManifest } from "@site/schema";

export const manifest: TemplateManifest = {
  "id": "spacex-ipo",
  "name": "Spacex Ipo",
  "description": "Imported from spacex-ipo.",
  "version": "1.0.0",
  "previewImage": "_templates/spacex-ipo@1.0.0/preview.png",
  "rendererKey": "slotted",
  "flow": "vertical",
  "supportedSectionTypes": [
    "prose"
  ],
  "sectionCount": {
    "min": 3,
    "max": 3
  },
  "supportsModules": [
    "token"
  ],
  "requiredContent": [
    "hero.title",
    "meta.title"
  ],
  "dependencies": [],
  "imageAspect": {
    "hero": "16/9",
    "section": "16/9",
    "card": "4/3",
    "gallery": "1/1"
  },
  "usesThemeKeys": [
    "core.button.textTransform",
    "core.colors.background",
    "core.colors.onPrimary",
    "core.colors.overlay",
    "core.colors.primary",
    "core.colors.primaryHover",
    "core.colors.text",
    "core.colors.textMuted",
    "core.motion.speed",
    "core.spacing.contentMaxInline",
    "core.spacing.sectionPaddingBlock",
    "core.spacing.sectionPaddingInline",
    "core.typography.baseFontSize",
    "core.typography.fontFamilyBase",
    "core.typography.headingTransform",
    "core.typography.kickerTransform",
    "core.typography.letterSpacingWide",
    "core.typography.lineHeightBase",
    "core.typography.lineHeightHeading",
    "semantic.footerBackground",
    "semantic.footerBorder",
    "semantic.footerForeground",
    "semantic.mobileMenuBackground",
    "semantic.navBackground",
    "semantic.navForeground"
  ],
  "customThemeSchema": {
    "headerBlur": {
      "type": "select",
      "label": "Header Blur",
      "default": "blur(8px)"
    },
    "sectionMinHeight": {
      "type": "length",
      "label": "Section Min Height",
      "default": "100vh"
    }
  },
  "capabilities": {
    "hasStickyNav": true,
    "hasMobileDrawer": true,
    "supportsPerSectionBackground": true
  },
  "kind": "slotted",
  "slotted": {
    "sourceKey": "spacex-ipo@1.0.0",
    "slots": [
      {
        "selector": "#launch .kicker",
        "path": "hero.kicker",
        "mode": "text"
      },
      {
        "selector": "#launch .content h1",
        "path": "hero.title",
        "mode": "text"
      },
      {
        "selector": "#launch .content p:nth-of-type(1)",
        "path": "hero.body[0]",
        "mode": "text"
      },
      {
        "selector": "#launch .content p:nth-of-type(2)",
        "path": "hero.body[1]",
        "mode": "text"
      },
      {
        "selector": "#launch .btn #textToCopy",
        "path": "modules.token.contractAddress",
        "mode": "text"
      },
      {
        "selector": "#launch .btn > div:not([id])",
        "path": "modules.token.copyLabel",
        "mode": "text"
      },
      {
        "selector": "#ipo .kicker",
        "path": "sections[0].kicker",
        "mode": "text"
      },
      {
        "selector": "#ipo .content h2",
        "path": "sections[0].title",
        "mode": "text"
      },
      {
        "selector": "#ipo .content p:nth-of-type(2)",
        "path": "sections[0].body[0]",
        "mode": "text"
      },
      {
        "selector": "#offering .kicker",
        "path": "sections[1].kicker",
        "mode": "text"
      },
      {
        "selector": "#offering .content h2",
        "path": "sections[1].title",
        "mode": "text"
      },
      {
        "selector": "#offering .content p:nth-of-type(1)",
        "path": "sections[1].body[0]",
        "mode": "text"
      },
      {
        "selector": "#offering .content p:nth-of-type(2)",
        "path": "sections[1].body[1]",
        "mode": "text"
      },
      {
        "selector": "#coin .kicker",
        "path": "sections[2].kicker",
        "mode": "text"
      },
      {
        "selector": "#coin .content h2",
        "path": "sections[2].title",
        "mode": "text"
      },
      {
        "selector": "#coin .content p",
        "path": "sections[2].body[0]",
        "mode": "text"
      },
      {
        "selector": "#coin .btn",
        "path": "sections[2].cta",
        "mode": "link"
      }
    ],
    "repeaters": [],
    "sanitize": {
      "approvedScripts": [],
      "allowedOrigins": [],
      "stripSelectors": []
    },
    "metaInsertSelector": "head",
    "rewriteAnchors": true,
    "sectionNodes": [
      {
        "path": "sections[0]",
        "selector": "#ipo",
        "navSelector": "a[href$=\"#ipo\"]"
      },
      {
        "path": "sections[1]",
        "selector": "#offering",
        "navSelector": "a[href$=\"#offering\"]"
      },
      {
        "path": "sections[2]",
        "selector": "#coin",
        "navSelector": "a[href$=\"#coin\"]"
      }
    ],
    "cssBackgrounds": [
      {
        "path": "hero.backgroundImage",
        "selector": ".hero",
        "pseudo": "before"
      },
      {
        "path": "sections[0].backgroundImage",
        "selector": ".starship",
        "pseudo": "before"
      },
      {
        "path": "sections[1].backgroundImage",
        "selector": ".human",
        "pseudo": "before"
      },
      {
        "path": "sections[2].backgroundImage",
        "selector": ".network",
        "pseudo": "before"
      }
    ],
    "cssScrims": [
      {
        "path": "hero.overlayOpacity",
        "selector": "#launch",
        "pseudo": "after"
      },
      {
        "path": "sections[0].overlayOpacity",
        "selector": "#ipo",
        "pseudo": "after"
      },
      {
        "path": "sections[1].overlayOpacity",
        "selector": "#offering",
        "pseudo": "after"
      },
      {
        "path": "sections[2].overlayOpacity",
        "selector": "#coin",
        "pseudo": "after"
      }
    ],
    "bundleAssets": [
      {
        "path": "assets/fontawesome/css/fontawesome.css",
        "integrity": "sha384-+DNG9ViMNGni41xCMRferX1b/hzZcFcfbdDz/Te2GTTpaAFeKODzrWUyDzczC8dp",
        "contentType": "text/css"
      },
      {
        "path": "assets/fontawesome/css/brands.css",
        "integrity": "sha384-SPEw8qBv9YYirHxFAoYMypag7EhmMjLKGS41mqzLJ7rFmByvAH+LcK+9+bbDjwr2",
        "contentType": "text/css"
      },
      {
        "path": "assets/favicon/favicon-96x96.png",
        "integrity": "sha384-7LaM6pnQ6Qb+7oP8fEr76JcjAGDby0bYUGwidhlXUue4HE+YMi55ZoGdsg+j9ISJ",
        "contentType": "image/png"
      },
      {
        "path": "assets/favicon/favicon.svg",
        "integrity": "sha384-HIOfW5LtFpmXFpIE1YzvUM/W3Fia53DvgNyGvKGuY9XgAaaL8BRyhqrpHZyobRc8",
        "contentType": "image/svg+xml"
      },
      {
        "path": "assets/favicon/favicon.ico",
        "integrity": "sha384-WdOHkFN24d1VquOs+jCrOkmkG0tg4dBEp/29FAsIHpxtkNi2zzEG5hSoge/Gi4Yu",
        "contentType": "image/x-icon"
      },
      {
        "path": "assets/favicon/apple-touch-icon.png",
        "integrity": "sha384-fsrdHZlrPCtn3yyN/0UeyCHnTirk06oQsf53eYYqk4fblwSFh62gtiSH5oNJv+ne",
        "contentType": "image/png"
      },
      {
        "path": "assets/favicon/site.webmanifest",
        "integrity": "sha384-wm1xu04vsP5vYGQmJd0iih9CObx5uzL79Z3+ermmeTyRtvLfrC/KjXYT35NlWKZh",
        "contentType": "application/manifest+json"
      }
    ],
    "sourceHash": "cc12a8f81207f3687beecc84558e3e9a78fcd133bc658c52251bead96e72ef38",
    "cssTokenized": {
      "source": "inline",
      "cssHash": "83e0c26096c886a0dc8572b6fdbf7cf51b3d94e2bf485fc4a56721b1ad9df4d1"
    }
  }
} as TemplateManifest;
