
import { z } from "zod";
import { field } from './field-meta';

/** Bump on any breaking shape change. Persisted with every stored payload. */
export const SCHEMA_VERSION = 1 as const;



// ============================================================================
// SECTION 2 — src/primitives.ts
// ============================================================================

/**
 * A value that may vary by breakpoint. Use sparingly — each responsive field
 * becomes three form controls. Reserve for things that genuinely change shape
 * (type scale, section sizing, template flow direction).
 */
export const responsive = <T extends z.ZodType>(inner: T) =>
  z.union([
    inner,
    z.object({ base: inner, md: inner.optional(), lg: inner.optional() }),
  ]);

export const CrossAlignSchema = z.enum(["start", "center", "end"]);
export type CrossAlign = z.infer<typeof CrossAlignSchema>;

export const TextTransformSchema = z.enum([
  "none", "uppercase", "lowercase", "capitalize",
]);

/**
 * Structured image reference. Deliberately not a bare URL.
 *
 * MEDIA LIFECYCLE — this is the part reconciled with the implementation plan:
 *
 *   Upload  → `variants` are generated by sharp at full source aspect
 *             (2400/1200/600px wide). Focal-INDEPENDENT, so a focal-point nudge
 *             never triggers regeneration.
 *   Editing → the form previews crops purely in CSS via aspect-ratio +
 *             object-position derived from focalX/focalY. No server round trip.
 *   Publish → the build generates the exact crops the selected template's
 *             `imageAspect` calls for, using the final focal point, and writes
 *             them to the site's S3 prefix.
 *
 * `stagingKey` points at Supabase Storage (mutable, user-owned).
 * `publishedKey` is populated by the build and lives in the version snapshot.
 */
export const ImageAssetSchema = z.object({
  /** Stable id, so variants and crops can be addressed independently of name. */
  id: z.string(),

  /** Supabase Storage object key for the original upload. */
  stagingKey: z.string(),

  /**
   * Resolvable URL for editor/preview use. Not what ships.
   *
   * Accepts an absolute URL (a real upload's staging URL) OR a root-relative
   * path (a seed image's /seed/{seedPath}/... — there is no real CDN host to
   * build an absolute URL from at import time, and nothing in this package
   * ever reads `url` for actual render output regardless: templates resolve
   * through TemplateContext.imageUrl(), never this field, directly).
   * Deliberately not just z.string().min(1) — that would also accept a bare
   * "TODO" or an empty-looking garbage string with no format signal at all.
   */
  url: field(
    z.string().refine(
      (v) => /^https?:\/\//i.test(v) || v.startsWith("/"),
      { message: "Must be an absolute URL or a root-relative path" },
    ),
    { label: "Image", widget: "image" },
  ),

  alt: field(z.string(), {
    label: "Alt text",
    help: "Describe the image for screen readers. Leave blank only if decorative.",
    widget: "text",
  }),

  /** True → emits alt="" and aria-hidden. Suppresses the missing-alt warning. */
  decorative: field(z.boolean().default(false), {
    label: "Decorative (carries no meaning)", widget: "toggle",
  }),

  width: z.number().int().positive().optional(),
  height: z.number().int().positive().optional(),

  /**
   * Focal point, 0..1, default centre. Drives object-position in preview and
   * the crop origin at publish, so one source survives 21:9 and 9:16.
   */
  focalX: field(z.number().min(0).max(1).default(0.5), {
    label: "Focal point", widget: "focalPoint",
  }),
  focalY: z.number().min(0).max(1).default(0.5),

  /** Upload-time size variants, keyed by width. Focal-independent. */
  variants: z.record(z.string(), z.string()).default({}),

  /** Populated by the build: S3 keys of the published crops, keyed by aspect. */
  publishedKeys: z.record(z.string(), z.string()).optional(),

  /** Base64 LQIP or blurhash. */
  placeholder: z.string().optional(),

    /**
   * Set ONLY on images shipped with a template preset.
   *
   * Path under the template's published prefix, e.g. "hero" for
   * `_templates/{templateId}@{version}/seed/hero/`. Its presence routes the
   * publish-time copy at the template prefix (server-side S3 CopyObject, same
   * as bundleAssets and vendor packages) instead of a Supabase Storage
   * download — and, because uploading a replacement produces an ImageAsset
   * without it, its presence is also the exact test for "still the seed image".
   *
   * `variants` is populated by the import script from the same
   * 2400/1200/600 webp generation the upload path uses, so focal handling,
   * crop geometry and srcset emission stay one code path.
   */
  seedPath: z.string().optional(),
 
// `stagingKey` holds the template-prefix key for seed images. It means "where
// the source bytes live", which is honest in both cases. `url` holds the
// published CDN URL, so preview needs no special case and no signing.
});
export type ImageAsset = z.infer<typeof ImageAssetSchema>;

export const SiteCtaSchema = z.object({
  label: field(z.string().min(1), { label: "Button text", widget: "text" }),
  href: field(z.string().min(1), { label: "Button link", widget: "url" }),
  /** Drives target="_blank" + rel="noopener noreferrer". */
  external: z.boolean().default(false),
  variant: z.enum(["primary", "secondary", "outline", "ghost"]).default("primary"),
});
export type SiteCta = z.infer<typeof SiteCtaSchema>;

/**
 * `platform` doubles as the icon lookup key against the resolved iconset, so
 * it must match a glyph name in the template's declared icon package
 * (e.g. "x-twitter", "telegram", "discord").
 */
export const SocialLinkSchema = z.object({
  id: z.string(),
  platform: field(z.string().min(1), { label: "Platform", widget: "icon" }),
  /** Accessible name — icon-only links are otherwise unlabelled. */
  label: field(z.string().min(1), { label: "Accessible label", widget: "text" }),
  url: field(z.string().url(), { label: "URL", widget: "url" }),
  showInNav: z.boolean().default(true),
  showInHero: z.boolean().default(false),
});
export type SocialLink = z.infer<typeof SocialLinkSchema>;